import {Course} from "@/types/course";

export const mockCourses: Course[] = [
    {
        id: "1",
        title: "Master UI/UX Design",
        categoryId: "design",
        categoryName: "Design",
        instructorId: "i1",
        instructorName: "Angela Yu",
        duration: "12h 30m",
        totalLessons: 48,
        description: "Learn modern UI/UX design principles.",
        whatYouWillLearn: ["Figma", "Wireframing", "Prototyping"],
        rating: 4.9,
        reviewsCount: 2450,
        price: 7.99,
        oldPrice: 120,
        imageUrl:
            "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        badge: "BEST SELLER",
    },
    {
        id: "2",
        title: "React Native Advanced",
        categoryId: "mobile",
        categoryName: "Mobile Dev",
        instructorId: "i2",
        instructorName: "Bruno Simon",
        duration: "18h 10m",
        totalLessons: 72,
        description: "Advanced React Native patterns and architecture.",
        whatYouWillLearn: ["Navigation", "State Mgmt", "Performance"],
        rating: 4.8,
        reviewsCount: 1890,
        price: 8.99,
        oldPrice: 140,
        imageUrl:
            "https://images.unsplash.com/photo-1518770660439-4636190af475",
        badge: "POPULAR",
    },
    {
        id: "3",
        title: "React Native Advanced",
        categoryId: "mobile",
        categoryName: "Mobile Dev",
        instructorId: "i2",
        instructorName: "Bruno Simon",
        duration: "18h 10m",
        totalLessons: 72,
        description: "Advanced React Native patterns and architecture.",
        whatYouWillLearn: ["Navigation", "State Mgmt", "Performance"],
        rating: 4.8,
        reviewsCount: 1890,
        price: 9.99,
        oldPrice: 140,
        imageUrl:
            "https://images.unsplash.com/photo-1518770660439-4636190af475",
        badge: "POPULAR",
    },
];