import { StyleSheet } from "react-native";
import { Colors } from "@/constants/colors";

export const curriculumStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FDF7FF",
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  content: {
    paddingBottom: 120,
  },
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FDF7FF",
    padding: 24,
  },
  centerStateText: {
    marginTop: 10,
    color: Colors.textSecondary,
    textAlign: "center",
  },
  errorTitle: {
    marginTop: 12,
    fontSize: 18,
    fontWeight: "700",
    color: "#1D1A24",
  },
  stepperContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
    marginBottom: 26,
  },
  stepCompleted: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  stepTextCompleted: {
    marginLeft: 8,
    fontSize: 14,
    color: "#494455",
  },
  line: {
    height: 2,
    width: 40,
    backgroundColor: Colors.primary,
    marginHorizontal: 16,
  },
  stepActive: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  stepTextActive: {
    color: Colors.white,
    fontWeight: "700",
  },
  stepTitleActive: {
    marginLeft: 8,
    fontSize: 16,
    color: Colors.primary,
    fontWeight: "700",
  },
  header: {
    marginBottom: 18,
  },
  kicker: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
  },
  title: {
    color: "#1D1A24",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 6,
  },
  subtitle: {
    color: Colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  metricsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 18,
  },
  metricCard: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E6E0EE",
    padding: 14,
  },
  metricValue: {
    color: Colors.primary,
    fontSize: 20,
    fontWeight: "800",
  },
  metricLabel: {
    color: Colors.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: Colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E6E0EE",
    padding: 24,
    marginTop: 6,
  },
  emptyTitle: {
    color: "#1D1A24",
    fontSize: 18,
    fontWeight: "800",
    marginTop: 12,
  },
  emptyText: {
    color: Colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
    marginBottom: 16,
    textAlign: "center",
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: Colors.white,
    fontWeight: "800",
  },
  sectionCard: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#E6E0EE",
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionNumber: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#F0E9FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  sectionNumberText: {
    color: Colors.primary,
    fontWeight: "800",
  },
  sectionTitleWrap: {
    flex: 1,
  },
  sectionTitle: {
    color: "#1D1A24",
    fontSize: 17,
    fontWeight: "800",
  },
  sectionMeta: {
    color: Colors.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionEmpty: {
    backgroundColor: "#F8F1FF",
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E6E0EE",
  },
  sectionEmptyText: {
    color: Colors.textSecondary,
    textAlign: "center",
  },
  lessonItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F1FF",
    padding: 10,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E6E0EE",
  },
  lessonIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.white,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  lessonBody: {
    flex: 1,
  },
  lessonTitle: {
    color: "#1D1A24",
    fontSize: 14,
    fontWeight: "700",
  },
  lessonMeta: {
    color: Colors.textSecondary,
    fontSize: 12,
    marginTop: 3,
  },
  addLessonButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.primary,
    borderStyle: "dashed",
    borderRadius: 10,
    marginTop: 8,
    padding: 12,
    gap: 6,
  },
  addLessonText: {
    color: Colors.primary,
    fontWeight: "800",
  },
  addSectionBtn: {
    minHeight: 76,
    borderWidth: 2,
    borderColor: "#CAC3D8",
    borderStyle: "dashed",
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  addSectionIconBg: {
    backgroundColor: "#F0E9FF",
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  addSectionText: {
    color: "#494455",
    fontSize: 16,
    fontWeight: "800",
  },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: "#E6E0EE",
    padding: 16,
  },
  publishButton: {
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  publishButtonText: {
    color: Colors.white,
    fontWeight: "800",
    fontSize: 16,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.34)",
    justifyContent: "center",
    padding: 18,
  },
  modalCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 18,
  },
  lessonModalCard: {
    maxHeight: "92%",
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 18,
  },
  lessonModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  modalTitle: {
    color: "#1D1A24",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 14,
  },
  label: {
    color: Colors.textPrimary,
    fontWeight: "700",
    marginBottom: 7,
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: Colors.textPrimary,
    marginBottom: 12,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  choiceChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E6E0EE",
    backgroundColor: "#F8F1FF",
  },
  choiceChipActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  choiceText: {
    color: Colors.primary,
    fontWeight: "700",
  },
  choiceTextActive: {
    color: Colors.white,
  },
  resourceHeader: {
    marginTop: 8,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  resourceTitle: {
    color: "#1D1A24",
    fontSize: 16,
    fontWeight: "800",
  },
  smallButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#F0E9FF",
  },
  smallButtonText: {
    color: Colors.primary,
    fontWeight: "800",
  },
  helperText: {
    color: Colors.textSecondary,
    marginBottom: 12,
  },
  formErrorText: {
    color: "#ba1a1a",
    fontSize: 12,
    marginTop: -6,
    marginBottom: 10,
  },
  resourceFormCard: {
    borderWidth: 1,
    borderColor: "#E6E0EE",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    backgroundColor: "#FBFAFF",
  },
  resourceFormHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  resourceFormTitle: {
    color: Colors.textPrimary,
    fontWeight: "800",
  },
  resourceChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E6E0EE",
    backgroundColor: Colors.white,
  },
  resourceChipText: {
    color: Colors.primary,
    fontWeight: "700",
    fontSize: 12,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 8,
  },
  secondaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  secondaryButtonText: {
    color: Colors.textPrimary,
    fontWeight: "800",
  },
  modalPrimaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: Colors.primary,
  },
  modalPrimaryButtonText: {
    color: Colors.white,
    fontWeight: "800",
  },
});
