import { StyleSheet } from 'react-native';
import { Spacing } from '@/constants/spacing';

export const profileStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F5F6F8' },
    content: { padding: Spacing.lg, paddingBottom: 40 },
    header: { marginBottom: 24 },
    appName: { fontSize: 22, fontWeight: '700', color: '#6C3EF4' },
    userCard: {
        backgroundColor: '#fff', borderRadius: 20, padding: 20,
        alignItems: 'center', marginBottom: 24,
        shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, elevation: 3,
    },
    avatarContainer: { position: 'relative', marginBottom: 12 },
    avatar: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#ddd' },
    avatarPlaceholder: { backgroundColor: '#e0e0e0', alignItems: 'center', justifyContent: 'center' },
    avatarPlaceholderText: { fontSize: 40 },
    editIconBadge: {
        position: 'absolute', bottom: 0, right: 0, backgroundColor: '#6C3EF4',
        borderRadius: 20, width: 32, height: 32, alignItems: 'center', justifyContent: 'center',
        borderWidth: 2, borderColor: '#fff',
    },
    editIcon: { color: '#fff', fontSize: 16 },
    userName: { fontSize: 20, fontWeight: '600', marginBottom: 4 },
    userEmail: { fontSize: 14, color: '#666', marginBottom: 12 },
    editButton: { backgroundColor: '#6C3EF4', paddingHorizontal: 20, paddingVertical: 8, borderRadius: 20 },
    editButtonText: { color: '#fff', fontWeight: '500' },
    statsRow: {
        flexDirection: 'row', backgroundColor: '#fff', borderRadius: 16,
        padding: 16, marginBottom: 24, justifyContent: 'space-around', alignItems: 'center',
    },
    statBox: { flex: 1, alignItems: 'center' },
    statNumber: { fontSize: 28, fontWeight: '700', color: '#6C3EF4' },
    statLabel: { fontSize: 12, color: '#888', marginTop: 4 },
    statDivider: { width: 1, height: 40, backgroundColor: '#ddd' },
    section: { backgroundColor: '#fff', borderRadius: 16, paddingVertical: 8, marginBottom: 24 },
    sectionTitle: {
        fontSize: 14, fontWeight: '600', color: '#888',
        paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f0f0f0',
    },
    settingItem: {
        flexDirection: 'row', justifyContent: 'space-between',
        paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#f5f5f5',
    },
    settingText: { fontSize: 16, color: '#333' },
    arrow: { fontSize: 20, color: '#bbb' },
    logoutButton: {
        backgroundColor: '#fff', borderRadius: 12, paddingVertical: 14,
        alignItems: 'center', marginBottom: 20, borderWidth: 1, borderColor: '#ff4444',
    },
    logoutText: { color: '#ff4444', fontWeight: '600', fontSize: 16 },
    version: { textAlign: 'center', color: '#aaa', fontSize: 12 },
    loading: { textAlign: 'center', marginTop: 40, color: '#888' },
    error: { textAlign: 'center', marginTop: 40, color: 'red' },
    modalContent: { backgroundColor: '#fff', borderRadius: 20, padding: 20 },
    modalTitle: { fontSize: 20, fontWeight: '600', marginBottom: 16, textAlign: 'center' },
    modalButtons: { flexDirection: 'row', gap: 12, marginTop: 16 },
    fullScreenModal: { margin: 0, justifyContent: 'center' },
    cameraContainer: { flex: 1, backgroundColor: '#000', justifyContent: 'center' },
    camera: { flex: 1 },
    closeCamera: { position: 'absolute', bottom: 40, alignSelf: 'center', backgroundColor: '#fff', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 30 },
    closeCameraText: { fontWeight: '600' },
    uploadingOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
});