import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';
import { Spacing } from '@/constants/spacing';

export const profileStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.background },
    content: { padding: Spacing.lg, paddingBottom: 40 },
    header: { marginBottom: 18 },
    appName: { fontSize: 24, fontWeight: '800', color: Colors.primary },
    pageSubtitle: { color: Colors.textSecondary, marginTop: 4, fontSize: 14 },
    userCard: {
        backgroundColor: Colors.surface, borderRadius: 18, padding: 22,
        alignItems: 'center', marginBottom: 24,
        borderWidth: 1, borderColor: Colors.muted,
        shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, elevation: 3,
    },
    avatarContainer: { position: 'relative', marginBottom: 12 },
    avatar: { width: 104, height: 104, borderRadius: 52, backgroundColor: Colors.muted },
    avatarPlaceholder: { backgroundColor: '#EEE8FF', alignItems: 'center', justifyContent: 'center' },
    avatarPlaceholderText: { fontSize: 13, fontWeight: '700', color: Colors.primary },
    editIconBadge: {
        position: 'absolute', bottom: 2, right: 2, backgroundColor: Colors.primary,
        borderRadius: 20, width: 32, height: 32, alignItems: 'center', justifyContent: 'center',
        borderWidth: 2, borderColor: Colors.white,
    },
    editIcon: { color: Colors.white, fontSize: 16 },
    userName: { fontSize: 22, fontWeight: '800', color: Colors.textPrimary, marginBottom: 4 },
    userEmail: { fontSize: 14, color: Colors.textSecondary, marginBottom: 14 },
    roleBadge: {
        backgroundColor: '#EEE8FF',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 5,
        marginBottom: 14,
    },
    roleBadgeText: { color: Colors.primary, fontSize: 12, fontWeight: '800' },
    editButton: { backgroundColor: Colors.primary, paddingHorizontal: 20, paddingVertical: 10, borderRadius: 12 },
    editButtonText: { color: Colors.white, fontWeight: '700' },
    instructorCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surface,
        borderRadius: 14,
        padding: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#E3DAFF',
    },
    instructorIcon: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: '#EEE8FF',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    instructorContent: { flex: 1 },
    instructorTitle: { fontSize: 16, fontWeight: '800', color: Colors.textPrimary, marginBottom: 2 },
    instructorSubtitle: { fontSize: 12, color: Colors.textSecondary },
    instructorButton: {
        backgroundColor: Colors.primary,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
    },
    instructorButtonText: { color: Colors.white, fontWeight: '700' },
    statsRow: {
        flexDirection: 'row', backgroundColor: Colors.surface, borderRadius: 14,
        padding: 16, marginBottom: 24, justifyContent: 'space-around', alignItems: 'center',
        borderWidth: 1, borderColor: Colors.muted,
    },
    statBox: { flex: 1, alignItems: 'center' },
    statNumber: { fontSize: 28, fontWeight: '800', color: Colors.primary },
    statLabel: { fontSize: 12, color: Colors.textSecondary, marginTop: 4 },
    statDivider: { width: 1, height: 40, backgroundColor: Colors.muted },
    section: {
        backgroundColor: Colors.surface,
        borderRadius: 14,
        paddingVertical: 8,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: Colors.muted,
    },
    sectionTitle: {
        fontSize: 14, fontWeight: '800', color: Colors.textPrimary,
        paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.muted,
    },
    settingItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F3F5',
    },
    settingInfo: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    settingIcon: {
        width: 34,
        height: 34,
        borderRadius: 10,
        backgroundColor: '#EEE8FF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    settingText: { fontSize: 15, fontWeight: '600', color: Colors.textPrimary },
    arrow: { fontSize: 20, color: '#A0A7B1' },
    logoutButton: {
        backgroundColor: '#FFF5F5', borderRadius: 12, paddingVertical: 14,
        alignItems: 'center', marginBottom: 20, borderWidth: 1, borderColor: '#FCA5A5',
    },
    logoutText: { color: '#DC2626', fontWeight: '700', fontSize: 16 },
    version: { textAlign: 'center', color: Colors.textSecondary, fontSize: 12 },
    loading: { textAlign: 'center', marginTop: 40, color: Colors.textSecondary },
    error: { textAlign: 'center', marginTop: 40, color: '#DC2626' },
    modalContent: { backgroundColor: Colors.surface, borderRadius: 18, padding: 20 },
    modalTitle: { fontSize: 20, fontWeight: '800', marginBottom: 16, textAlign: 'center', color: Colors.textPrimary },
    modalButtons: { flexDirection: 'row', gap: 12, marginTop: 16 },
    fullScreenModal: { margin: 0, justifyContent: 'center' },
    cameraContainer: { flex: 1, backgroundColor: '#000', justifyContent: 'center' },
    camera: { flex: 1 },
    closeCamera: { position: 'absolute', bottom: 40, alignSelf: 'center', backgroundColor: '#fff', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 30 },
    closeCameraText: { fontWeight: '600' },
    uploadingOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
});
